# Values for loki-stack helm chart (Grafana + Loki + Promtail)
# Optimized for local k3d

loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 2Gi
  config:
    auth_enabled: false

promtail:
  enabled: true
  config:
    logLevel: info

grafana:
  enabled: true
  adminPassword: "AdmiralBashIsAwesome"
  # Decision: Ingress generation is disabled. We manually define HTTPRoute objects
  # to demonstrate the Gateway API paradigm.
  ingress:
    enabled: false
    path: /
  sidecar:
    datasources:
      enabled: true
